site_name: dbMAP
nav:
    - Home: index.md
    - Install: installation.md
    - API: docs.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - R
        - python
        - bash
